version: "3.9"
services:
  # MySQLコンテナの設定
  db:
    container_name: db-container
    image: mysql:8.0.31
    platform: linux/amd64
    ports:
      - "$DB_CONTAINER_PORT:$DB_CONTAINER_PORT"
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      TZ: $TZ
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/mysql_data:/var/lib/mysql
      - ./db/logs:/var/log/mysql
    tty: true
    networks:
      backend:
        ipv4_address: $DB_CONTAINER_IPV4 # コンテナのIPアドレス
  # Node.js + Expressコンテナの設定
  api:
    container_name: api-container
    image: test-express-server:16.19
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
    ports:
      - "3000:3000"
    working_dir: /express
    command: node index.js
    depends_on:
      - db # MySQLコンテナが起動した後に起動
    env_file:
      - .env
    tty: true
    networks:
      backend:
        ipv4_address: $API_CONTAINER_IPV4 # コンテナのIPアドレス
# ネットワーク設定
networks:
  backend:
    driver: bridge
    name: app_network
    ipam:
      config:
        - subnet: $SUBNET
